import type { Metadata } from "next";
import { ReactNode } from "react";
import "../../../styles/index.css";
import Pwa from "./Pwa";
import HeaderComponent from "../shared/Header";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function PublicLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en" className="overflow-x-hidden">
            <body className="bg-[#010207] text-white overflow-x-hidden">
                <Pwa>
                    <HeaderComponent />
                    {children}
                </Pwa>
            </body>
        </html>
    );
}