import type { Metadata } from "next";
import { ReactNode } from "react";
import "../../../styles/index.css";
import Pwa from "./Pwa";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function PublicLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Pwa>
                    {children}
                </Pwa>
            </body>
        </html>
    );
}